In [1]:
import pandas as pd

data = {
    'Area': [800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 
             2800, 3000, 3200, 3400, 3600, 3800, 4000, 4200, 4400, 4600],
    'Price': [120000, 150000, 180000, 200000, 220000, 250000, 280000, 300000,
              320000, 350000, 380000, 400000, 420000, 450000, 480000, 500000,
              520000, 550000, 580000, 600000]
}

df = pd.DataFrame(data)
print(df)


    Area   Price
0    800  120000
1   1000  150000
2   1200  180000
3   1400  200000
4   1600  220000
5   1800  250000
6   2000  280000
7   2200  300000
8   2400  320000
9   2600  350000
10  2800  380000
11  3000  400000
12  3200  420000
13  3400  450000
14  3600  480000
15  3800  500000
16  4000  520000
17  4200  550000
18  4400  580000
19  4600  600000


In [5]:
df.to_excel('lands_prices.xlsx', index=False)

In [6]:
new_df=pd.read_excel('lands_prices.xlsx')

In [8]:
new_df.head()

Area   Price
0   800  120000
1  1000  150000
2  1200  180000
3  1400  200000
4  1600  220000

In [9]:
from sklearn.model_selection import train_test_split

In [11]:
X=df[['Area']]
y=df['Price']

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

In [20]:
from sklearn.linear_model import LinearRegression


In [21]:
model=LinearRegression()

In [22]:
model.fit(X_train,y_train)

LinearRegression()

In [23]:
model.score(X_test,y_test)

0.9998160850973377

In [24]:
predictions= model.predict(X_test)

In [29]:
model.predict([[800]])

C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([125290.3031217])

In [32]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Creating the DataFrame from the provided data
data = {
    'Area': [800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 
             2800, 3000, 3200, 3400, 3600, 3800, 4000, 4200, 4400, 4600],
    'Price': [120000, 150000, 180000, 200000, 220000, 250000, 280000, 300000,
              320000, 350000, 380000, 400000, 420000, 450000, 480000, 500000,
              520000, 550000, 580000, 600000]
}

df = pd.DataFrame(data)

# Separating features (X) and target variable (y)
X = df[['Area']]
y = df['Price']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Training the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Evaluating the model's performance
train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print("Training R^2 Score:", train_score)
print("Testing R^2 Score:", test_score)

# Making predictions for a new data point
new_area = [[800]]  # New area value for prediction
predicted_price = model.predict(new_area)
print("Predicted Price for Area 800:", predicted_price)


Training R^2 Score: 0.9991382924606584
Testing R^2 Score: 0.9998160850973377
Predicted Price for Area 800: [125290.3031217]


C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [33]:
# Making predictions for a new data point
new_area = [[800]]  # New area value for prediction (reshaped into 2D array)
predicted_price = model.predict(new_area)
print("Predicted Price for Area 800:", predicted_price)


Predicted Price for Area 800: [125290.3031217]


C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [34]:
# Printing coefficients and intercept
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)


Coefficients: [125.01131051]
Intercept: 25281.254712713184


In [1]:
#Multiple Linear Regression

In [2]:
import pandas as pd

# Creating a DataFrame for multilinear regression
data = {
    'Area': [800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 
             2800, 3000, 3200, 3400, 3600, 3800, 4000, 4200, 4400, 4600],
    'Rooms': [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8],
    'Distance_to_city_center': [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 
                                 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
    'Price': [120000, 150000, 180000, 200000, 220000, 250000, 280000, 300000,
              320000, 350000, 380000, 400000, 420000, 450000, 480000, 500000,
              520000, 550000, 580000, 600000]
}

df = pd.DataFrame(data)

print(df)


    Area  Rooms  Distance_to_city_center   Price
0    800      1                        5  120000
1   1000      2                        6  150000
2   1200      2                        7  180000
3   1400      3                        8  200000
4   1600      3                        9  220000
5   1800      3                       10  250000
6   2000      4                       11  280000
7   2200      4                       12  300000
8   2400      4                       13  320000
9   2600      4                       14  350000
10  2800      5                       15  380000
11  3000      5                       16  400000
12  3200      5                       17  420000
13  3400      6                       18  450000
14  3600      6                       19  480000
15  3800      6                       20  500000
16  4000      7                       21  520000
17  4200      7                       22  550000
18  4400      7                       23  580000
19  4600      8     

In [3]:
df.head()

Area  Rooms  Distance_to_city_center   Price
0   800      1                        5  120000
1  1000      2                        6  150000
2  1200      2                        7  180000
3  1400      3                        8  200000
4  1600      3                        9  220000

In [8]:
df.to_csv('Multi_regression.csv', index=False)


In [10]:
df.head()

Area  Rooms  Distance_to_city_center   Price
0   800      1                        5  120000
1  1000      2                        6  150000
2  1200      2                        7  180000
3  1400      3                        8  200000
4  1600      3                        9  220000

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
from sklearn.linear_model import LinearRegression

In [15]:
X=df[['Area','Rooms','Distance_to_city_center']]

In [16]:
y=df['Price']

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [19]:
model=LinearRegression()

In [20]:
model

LinearRegression()

In [21]:
model.fit(X_train,y_train)

LinearRegression()

In [25]:
y_prediction=model.predict(X_test)

In [26]:
y_prediction

array([120638.29787234, 551063.82978723, 498829.78723404, 149468.08510638])

In [27]:
y_test

0     120000
17    550000
15    500000
1     150000
Name: Price, dtype: int64

In [32]:
import numpy as np

# Reshape the input into a 2D array
X_new = np.array([800, 1, 5]).reshape(1, -1)

# Make predictions
predicted_price = model.predict(X_new)


C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [33]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# Create a DataFrame with feature names
X = pd.DataFrame({
    'Area': [800, 1000, 1200],
    'Rooms': [1, 2, 3],
    'Distance_to_city_center': [5, 6, 7]
})

# Create target variable y
y = [120000, 150000, 180000]

# Create and fit the model
model = LinearRegression()
model.fit(X, y)


LinearRegression()

In [34]:
X_new = [[800, 1, 5]]

# Make predictions
predicted_price = model.predict(X_new)

# Print the predicted price
print("Predicted Price:", predicted_price)

Predicted Price: [120000.]


C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [38]:
from joblib import dump,load

In [39]:
from joblib import dump, load

In [42]:
dump(model,'file_new.joblib')

['file_new.joblib']

In [43]:
loaded_model=load('file_new.joblib')

In [48]:
import pandas as pd

# Create a DataFrame with the new sample and appropriate column names
new_sample_df = pd.DataFrame([[800, 1, 5]], columns=['Area', 'Rooms', 'Distance_to_city_center'])

# Make predictions
predict_prices = model.predict(new_sample_df)


In [49]:
predict_prices

array([120000.])