In [1]:
import pandas as pd

# Your data
data = {
    'Car Model': ['BMW X5', 'BMW X5', 'BMW X5', 'BMW X5', 'BMW X5', 'Audi A5', 'Audi A5', 'Audi A5', 'Audi A5', 'Mercedez Benz C class', 'Mercedez Benz C class', 'Mercedez Benz C class', 'Mercedez Benz C class'],
    'Mileage': [69000, 35000, 57000, 22500, 46000, 59000, 52000, 72000, 91000, 67000, 83000, 79000, 59000],
    'Sell Price($)': [18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000, 22000, 20000, 21000, 33000],
    'Age(yrs)': [6, 3, 5, 2, 4, 5, 5, 6, 8, 6, 7, 7, 5]
}

# Create a DataFrame from the data
df = pd.DataFrame(data)

# Write the DataFrame to an Excel file
df.to_excel('car_data.xlsx', index=False)

print("Data has been successfully written to car_data.xlsx.")


Data has been successfully written to car_data.xlsx.


In [2]:
import pandas as pd

In [4]:
df=pd.read_excel('car_data.xlsx')

In [5]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [6]:
from sklearn.preprocessing import LabelEncoder

# Sample dataset
data = {
    'City': ['New York', 'Paris', 'Tokyo', 'London', 'Paris', 'New York', 'Tokyo'],
    'Temperature': [28, 22, 30, 25, 23, 29, 31],
    'Humidity': [60, 45, 70, 55, 50, 65, 75],
    'Rainy': ['Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes']
}


In [7]:
data

{'City': ['New York',
  'Paris',
  'Tokyo',
  'London',
  'Paris',
  'New York',
  'Tokyo'],
 'Temperature': [28, 22, 30, 25, 23, 29, 31],
 'Humidity': [60, 45, 70, 55, 50, 65, 75],
 'Rainy': ['Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes']}

In [13]:
df

City  Temperature  Humidity Rainy
0  New York           28        60   Yes
1     Paris           22        45    No
2     Tokyo           30        70   Yes
3    London           25        55    No
4     Paris           23        50    No
5  New York           29        65   Yes
6     Tokyo           31        75   Yes

In [8]:
df=pd.DataFrame(data)

In [9]:
df

City  Temperature  Humidity Rainy
0  New York           28        60   Yes
1     Paris           22        45    No
2     Tokyo           30        70   Yes
3    London           25        55    No
4     Paris           23        50    No
5  New York           29        65   Yes
6     Tokyo           31        75   Yes

In [12]:
pd.get_dummies(df.City)

London  New York  Paris  Tokyo
0   False      True  False  False
1   False     False   True  False
2   False     False  False   True
3    True     False  False  False
4   False     False   True  False
5   False      True  False  False
6   False     False  False   True

In [11]:
dummies

London  New York  Paris  Tokyo
0   False      True  False  False
1   False     False   True  False
2   False     False  False   True
3    True     False  False  False
4   False     False   True  False
5   False      True  False  False
6   False     False  False   True

In [14]:
merged=pd.concat([df,dummies])

In [15]:
merged

City  Temperature  Humidity Rainy London New York  Paris  Tokyo
0  New York         28.0      60.0   Yes    NaN      NaN    NaN    NaN
1     Paris         22.0      45.0    No    NaN      NaN    NaN    NaN
2     Tokyo         30.0      70.0   Yes    NaN      NaN    NaN    NaN
3    London         25.0      55.0    No    NaN      NaN    NaN    NaN
4     Paris         23.0      50.0    No    NaN      NaN    NaN    NaN
5  New York         29.0      65.0   Yes    NaN      NaN    NaN    NaN
6     Tokyo         31.0      75.0   Yes    NaN      NaN    NaN    NaN
0       NaN          NaN       NaN   NaN  False     True  False  False
1       NaN          NaN       NaN   NaN  False    False   True  False
2       NaN          NaN       NaN   NaN  False    False  False   True
3       NaN          NaN       NaN   NaN   True    False  False  False
4       NaN          NaN       NaN   NaN  False    False   True  False
5       NaN          NaN       NaN   NaN  False     True  False  False
6       NaN          NaN       NaN   NaN  False    False  False   True

In [16]:
merged = pd.concat([df, dummies], axis=1).reset_index(drop=True)


In [17]:
merged

City  Temperature  Humidity Rainy  London  New York  Paris  Tokyo
0  New York           28        60   Yes   False      True  False  False
1     Paris           22        45    No   False     False   True  False
2     Tokyo           30        70   Yes   False     False  False   True
3    London           25        55    No    True     False  False  False
4     Paris           23        50    No   False     False   True  False
5  New York           29        65   Yes   False      True  False  False
6     Tokyo           31        75   Yes   False     False  False   True

In [19]:
final=merged.drop(['City'], axis='columns')

In [20]:
final

Temperature  Humidity Rainy  London  New York  Paris  Tokyo
0           28        60   Yes   False      True  False  False
1           22        45    No   False     False   True  False
2           30        70   Yes   False     False  False   True
3           25        55    No    True     False  False  False
4           23        50    No   False     False   True  False
5           29        65   Yes   False      True  False  False
6           31        75   Yes   False     False  False   True

In [28]:
X = final[['Temperature', 'Humidity', 'Rainy', 'London', 'New York', 'Paris', 'Tokyo']]
y = merged['City']

In [29]:
y

0    New York
1       Paris
2       Tokyo
3      London
4       Paris
5    New York
6       Tokyo
Name: City, dtype: object

In [31]:
# Assuming 'final' is your DataFrame without the 'City' column
X = final[['Temperature', 'Humidity', 'Rainy', 'London', 'New York', 'Paris', 'Tokyo']]
y = merged['City']  # Assuming you want to predict the original 'City' column

# Display X and y
print("X:")
print(X)
print("\ny:")
print(y)


X:
   Temperature  Humidity Rainy  London  New York  Paris  Tokyo
0           28        60   Yes   False      True  False  False
1           22        45    No   False     False   True  False
2           30        70   Yes   False     False  False   True
3           25        55    No    True     False  False  False
4           23        50    No   False     False   True  False
5           29        65   Yes   False      True  False  False
6           31        75   Yes   False     False  False   True

y:
0    New York
1       Paris
2       Tokyo
3      London
4       Paris
5    New York
6       Tokyo
Name: City, dtype: object


In [33]:
X

Temperature  Humidity Rainy  London  New York  Paris  Tokyo
0           28        60   Yes   False      True  False  False
1           22        45    No   False     False   True  False
2           30        70   Yes   False     False  False   True
3           25        55    No    True     False  False  False
4           23        50    No   False     False   True  False
5           29        65   Yes   False      True  False  False
6           31        75   Yes   False     False  False   True

In [34]:
y

0    New York
1       Paris
2       Tokyo
3      London
4       Paris
5    New York
6       Tokyo
Name: City, dtype: object

In [37]:
from sklearn.linear_model import LogisticRegression

# Initialize the model
model = LogisticRegression()


In [40]:
from sklearn.linear_model import LogisticRegression

# Assuming 'X' and 'y' are your feature matrix and target variable
model = LogisticRegression()

# Train the model on the entire dataset
model.fit(X, y)

# Now, you can make predictions on new data or the same data
y_pred = model.predict(X)


Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "C:\Users\91944\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\91944\AppData\Local\Temp\ipykernel_24644\1521777292.py", line 7, in <module>
    model.fit(X, y)
  File "C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1207, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\base.py", line 621, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\utils\validatio

In [41]:
# Assuming 'final' is your DataFrame without the 'City' column
final_encoded = pd.get_dummies(final, columns=['Rainy'], drop_first=True)

# Now, 'final_encoded' contains numerical values for the 'Rainy' column
X = final_encoded[['Temperature', 'Humidity', 'Rainy_Yes', 'London', 'New York', 'Paris', 'Tokyo']]
y = merged['City']

# Now, you can train your model
model.fit(X, y)


C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [42]:
from sklearn.linear_model import LogisticRegression

# Assuming 'X' and 'y' are your feature matrix and target variable
model = LogisticRegression(max_iter=1000)  # Increase max_iter

# Train the model on the entire dataset
model.fit(X, y)


LogisticRegression(max_iter=1000)

In [44]:
X


Temperature  Humidity  Rainy_Yes  London  New York  Paris  Tokyo
0           28        60       True   False      True  False  False
1           22        45      False   False     False   True  False
2           30        70       True   False     False  False   True
3           25        55      False    True     False  False  False
4           23        50      False   False     False   True  False
5           29        65       True   False      True  False  False
6           31        75       True   False     False  False   True

In [46]:
y

0    New York
1       Paris
2       Tokyo
3      London
4       Paris
5    New York
6       Tokyo
Name: City, dtype: object

In [48]:
import numpy as np

# Reshape the input array
input_data = np.array([28, 60, 1, 0, 1, 0, 0]).reshape(1, -1)

# Predict using the reshaped input
prediction = model.predict(input_data)

# Display the prediction
print("Predicted City:", prediction)


Predicted City: ['New York']


C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [49]:
model.score(X,y)

1.0

In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
labels=['red','green','blue','green']

In [3]:
label_encoder=LabelEncoder()

In [4]:
encoder_labels=label_encoder.fit_transform(labels)

In [5]:
print(labels)

['red', 'green', 'blue', 'green']


In [7]:
print("Original labels:", labels)
print("Encoded labels:", encoder_labels)

Original labels: ['red', 'green', 'blue', 'green']
Encoded labels: [2 1 0 1]


In [9]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [10]:
data={'Color': ['red','green','blue','greeen']}

In [11]:
df=pd.DataFrame(data)

In [16]:
onehot_encoder = OneHotEncoder(sparse_output=False)  # Use sparse_output instead of sparse

# Fit and transform the data
onehot_encoded = onehot_encoder.fit_transform(df[['Color']])


In [18]:

print(onehot_encoded)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [21]:
from sklearn.preprocessing import OrdinalEncoder

# Example data with extended values
education_levels = [
    ['High School'],
    ['Junior'],
    ['Senior'],
    ['High School'],
    ['Junior'],
    ['Senior'],
    ['High School'],
    ['Senior'],
    ['Junior']
]

# Create an Ordinal Encoder with specified order
ordinal_encoder = OrdinalEncoder(categories=[['High School', 'Junior', 'Senior']])

# Fit and transform the education levels
encoded_education_levels = ordinal_encoder.fit_transform(education_levels)

print("Original education levels:", education_levels)
print("Encoded education levels:", encoded_education_levels)


Original education levels: [['High School'], ['Junior'], ['Senior'], ['High School'], ['Junior'], ['Senior'], ['High School'], ['Senior'], ['Junior']]
Encoded education levels: [[0.]
 [1.]
 [2.]
 [0.]
 [1.]
 [2.]
 [0.]
 [2.]
 [1.]]


In [22]:
#Homework problem

In [27]:
import pandas as pd

# Given data
data = {
    'Car Model': ['BMW X5', 'BMW X5', 'BMW X5', 'BMW X5', 'BMW X5', 'Audi A5', 'Audi A5', 'Audi A5', 'Audi A5', 'Mercedes Benz C class', 'Mercedes Benz C class', 'Mercedes Benz C class', 'Mercedes Benz C class'],
    'Mileage': [69000, 35000, 57000, 22500, 46000, 59000, 52000, 72000, 91000, 67000, 83000, 79000, 59000],
    'Sell Price($)': [18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000, 22000, 20000, 21000, 33000],
    'Age(yrs)': [6, 3, 5, 2, 4, 5, 5, 6, 8, 6, 7, 7, 5]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the dataset
print(car_data)


                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedes Benz C class    67000          22000         6
10  Mercedes Benz C class    83000          20000         7
11  Mercedes Benz C class    79000          21000         7
12  Mercedes Benz C class    59000          33000         5


In [28]:
dummies = pd.get_dummies(df['Car Model'])
dummies

Audi A5  BMW X5  Mercedes Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [30]:
merged=pd.concat([df, dummies], axis='columns')

In [31]:
merged

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6    False    True   
1                  BMW X5    35000          34000         3    False    True   
2                  BMW X5    57000          26100         5    False    True   
3                  BMW X5    22500          40000         2    False    True   
4                  BMW X5    46000          31500         4    False    True   
5                 Audi A5    59000          29400         5     True   False   
6                 Audi A5    52000          32000         5     True   False   
7                 Audi A5    72000          19300         6     True   False   
8                 Audi A5    91000          12000         8     True   False   
9   Mercedes Benz C class    67000          22000         6    False   False   
10  Mercedes Benz C class    83000          20000         7    False   False   
11  Mercedes Benz C class    79000          21000         7    False   False   
12  Mercedes Benz C class    59000          33000         5    False   False   

    Mercedes Benz C class  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
5                   False  
6                   False  
7                   False  
8                   False  
9                    True  
10                   True  
11                   True  
12                   True

In [34]:
final = merged.drop(['Car Model', 'Mercedes Benz C class'], axis='columns')
print(final)

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6    False    True
1     35000          34000         3    False    True
2     57000          26100         5    False    True
3     22500          40000         2    False    True
4     46000          31500         4    False    True
5     59000          29400         5     True   False
6     52000          32000         5     True   False
7     72000          19300         6     True   False
8     91000          12000         8     True   False
9     67000          22000         6    False   False
10    83000          20000         7    False   False
11    79000          21000         7    False   False
12    59000          33000         5    False   False


In [36]:
x=final.drop('Sell Price($)',axis='columns')

In [37]:
x

Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6    False    True
1     35000         3    False    True
2     57000         5    False    True
3     22500         2    False    True
4     46000         4    False    True
5     59000         5     True   False
6     52000         5     True   False
7     72000         6     True   False
8     91000         8     True   False
9     67000         6    False   False
10    83000         7    False   False
11    79000         7    False   False
12    59000         5    False   False

In [38]:
y=final['Sell Price($)']

In [39]:
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [41]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [42]:
model.fit(x,y)

LinearRegression()

In [44]:
model.score(x,y)

0.9417050937281082

In [47]:
model.predict([[45000,4,0,0]])

C:\Users\91944\.anaconda\Anaconda_new\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36991.31721061])